### ISSUE TITLE
ws-qvh does not emit `spawn` event

### ISSUE THREAD

**Issue by inluxc** [NetrisTV/ws-scrcpy#116]
I there, first of all i know there is an FIXME in the code, i think it should be registed in issue 😄 

```
[QvhackRunner][udid: 00008030001550A4029A402E] failed to spawn process.
Error: spawn ws-qvh ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: spawn ws-qvh ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event at:
    at t.e.emit (/Users/username/Projects/ws-scrcpy/dist/index.js:1:3592)
    at ChildProcess.<anonymous> (/Users/username/Projects/ws-scrcpy/dist/index.js:1:57647)
    at ChildProcess.emit (events.js:375:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ws-qvh',
  path: 'ws-qvh',
  spawnargs: [ '127.0.0.1:8001' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ws-scrcpy@0.8.0-dev start: `node ./index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ws-scrcpy@0.8.0-dev start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2021-07-07T09_40_39_505Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ws-scrcpy@0.8.0-dev start: `npm run dist && cd dist && npm start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ws-scrcpy@0.8.0-dev start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2021-07-07T09_40_39_558Z-debug.log
The terminal process "zsh '-c', 'npm run start'" terminated with exit code: 1.
```

**Comment by drauggres** [comment]
Hi.
Make sure that `ws-qvh` is available in `PATH` env. `ENOENT` means that server cannot find it.
This `FIXME` is about a different issue.

**Comment by inluxc** [comment]
Yep i do have ws-qvh in the PATH env.

**Comment by drauggres** [comment]
> Yep i do have ws-qvh in the PATH env.

Well, node.js doesn't think so. You should place in `PATH` directory where `ws-qvh` lies, not including its name. For example:
> netris@stand ~ % ls -l /Users/netris/go/bin/ws-qvh
> -rwxr-xr-x  1 netris  staff  10182768 May  1 16:46 /Users/netris/go/bin/ws-qvh
>
> netris@stand ~ % echo $PATH
> /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/netris/go/bin

What happens if you run `ws-qvh` instead of `npm start` in the same terminal?

**Comment by inluxc** [comment]
Ok sorry, i need to restart vcs, i will close this issue.
