### ISSUE TITLE
Error: Cannot find module '../server/websocket.js'

### ISSUE THREAD

**Issue by botsphp** [NetrisTV/ws-scrcpy#12]
I got this error on Ubuntu14 and Mac OS,  does anyone seem this error before?

```shell

> cd public && npx ws --websocket ../server/websocket.js --spa index.html

Error: Cannot find module '../server/websocket.js'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.resolve (internal/module.js:18:19)
    at loadModule (/media/psf/Home/wwwroot/ws-scrcpy/node_modules/load-module/index.js:45:32)
    at Lws.attachWebsocket (/media/psf/Home/wwwroot/ws-scrcpy/node_modules/lws/index.js:140:62)
    at Lws.listen (/media/psf/Home/wwwroot/ws-scrcpy/node_modules/lws/index.js:77:12)
    at WsServe.execute (/media/psf/Home/wwwroot/ws-scrcpy/node_modules/lws/lib/command/serve.js:296:26)
    at WsServe.execute (/media/psf/Home/wwwroot/ws-scrcpy/node_modules/local-web-server/lib/command/serve.js:11:18)
    at Map.start (/media/psf/Home/wwwroot/ws-scrcpy/node_modules/cli-commands/index.js:26:18)
    at WsCliApp.start (/media/psf/Home/wwwroot/ws-scrcpy/node_modules/lws/lib/cli-app.js:9:26)
    at Function.run (/media/psf/Home/wwwroot/ws-scrcpy/node_modules/lws/lib/cli-app.js:15:29)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ws-scrcpy@0.1.0 start: `cd public && npx ws --websocket ../server/websocket.js --spa index.html`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ws-scrcpy@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:

````

**Comment by drauggres** [comment]
Hi. I assume you are using node v12?  Try with v10.

**Comment by slimsymphony** [comment]
Downgrade your node version lower than v13 than it may works well, since v13 node have changed its module find strategy.
