### ISSUE TITLE
Error: callback(): The callback was already called. on node v17

### ISSUE THREAD

**Issue by ender1324** [NetrisTV/ws-scrcpy#172]
/home/build/ws-scrcpy/node_modules/loader-runner/lib/LoaderRunner.js:106
                        throw new Error("callback(): The callback was already called.");
         ^
Error: callback(): The callback was already called.
    at Object.context.callback (/home/build/ws-scrcpy/node_modules/loader-runner/lib/LoaderRunner.js:106:10)
    at Object.module.exports (/home/build/ws-scrcpy/node_modules/ifdef-loader/ifdef-loader.js:51:14)
    at LOADER_EXECUTION (/home/build/ws-scrcpy/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/home/build/ws-scrcpy/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/home/build/ws-scrcpy/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/build/ws-scrcpy/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/build/ws-scrcpy/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/build/ws-scrcpy/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/build/ws-scrcpy/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

**Comment by ender1324** [comment]
if fixed from loaderrunner itself, it goes onto Error: Failed to init "aDevice Tracker [hostname]". connect ECONNREFUSED ::1:5037

**Comment by drauggres** [comment]
Hi.
Please try the latest version from the `master` branch.

**Comment by drauggres** [comment]
As for the problem in the title, you are right `NODE_OPTIONS=--openssl-legacy-provider` is the only solution, besides using older node version or migrating this project to `webpack@5`.
I would recommend to use node v16, since it is LTS.

More about the issue: https://github.com/webpack/webpack/issues/14532

**Comment by ender1324** [comment]
Yep

> Hi. Please try the latest version from the `master` branch.
> 
> UPD: `ECONNREFUSED ::1:5037` should be fixed.

Yep, that's fixed now, bedsides the main issue still remains, I'm not sure if this is a bug with LoaderRunner itself or with webpack

**Comment by drauggres** [comment]
> I'm not sure if this is a bug with LoaderRunner itself or with webpack

Problem is in node v17: they removed old hash algorithms, which were used in webpack@4 to hash modules (for caching). See the link in my previous comment.

**Comment by drauggres** [comment]
I updated webpack to the latest version in v4 branch.
Now you should see the actual error when you build the project with node v17.

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (./ws-scrcpy/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (./ws-scrcpy/node_modules/webpack/lib/NormalModule.js:417:16)
```
