### ISSUE TITLE
 Run in nodejs v12.8.0 

### ISSUE THREAD

**Issue by yewang422** [NetrisTV/ws-scrcpy#2]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ws-scrcpy@0.0.1~prestart: ws-scrcpy@0.0.1
6 info lifecycle ws-scrcpy@0.0.1~start: ws-scrcpy@0.0.1
7 verbose lifecycle ws-scrcpy@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle ws-scrcpy@0.0.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/yewang/data/project/xbw/ws-scrcpy/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/yewang/Library/Android/sdk/platform-tools
9 verbose lifecycle ws-scrcpy@0.0.1~start: CWD: /Users/yewang/data/project/xbw/ws-scrcpy
10 silly lifecycle ws-scrcpy@0.0.1~start: Args: [ '-c', 'npm run dist && cd dist && npm start' ]
11 silly lifecycle ws-scrcpy@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle ws-scrcpy@0.0.1~start: Failed to exec start script
13 verbose stack Error: ws-scrcpy@0.0.1 start: `npm run dist && cd dist && npm start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid ws-scrcpy@0.0.1
15 verbose cwd /Users/yewang/data/project/xbw/ws-scrcpy
16 verbose Darwin 18.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.4.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error ws-scrcpy@0.0.1 start: `npm run dist && cd dist && npm start`
22 error Exit status 1
23 error Failed at the ws-scrcpy@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by drauggres** [comment]
Hi, @yewang422.

There was a problem with `cp` command arguments on macOS.
Please try again with node `8.x` or `10.x` (there is still a problem with node `12.x`)
