### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by yycxx** [NetrisTV/ws-scrcpy#252]
> ws-scrcpy@0.8.0-dev start
> npm run dist && cd dist && npm start

> ws-scrcpy@0.8.0-dev dist
> npm run dist:prod

> ws-scrcpy@0.8.0-dev dist:prod
> webpack --config webpack/ws-scrcpy.prod.ts --env.config_override='./build.config.override.json'

/data/home/hanweb/project/python/project/JMCT3.0.3/app/src/ws-scrcpy/node_modules/ts-node/src/index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
webpack/ws-scrcpy.prod.ts:2:19 - error TS2305: Module '"../node_modules/webpack/types"' has no exported member 'ConfigurationFactory'.

2 import webpack, { ConfigurationFactory } from 'webpack';
                    ~~~~~~~~~~~~~~~~~~~~
webpack/ws-scrcpy.prod.ts:8:38 - error TS7006: Parameter 'env' implicitly has an 'any' type.

8 const front: ConfigurationFactory = (env, args) => {
                                       ~~~
webpack/ws-scrcpy.prod.ts:8:43 - error TS7006: Parameter 'args' implicitly has an 'any' type.

8 const front: ConfigurationFactory = (env, args) => {
                                            ~~~~
webpack/ws-scrcpy.prod.ts:11:37 - error TS7006: Parameter 'env' implicitly has an 'any' type.

11 const back: ConfigurationFactory = (env, args) => {
                                       ~~~
webpack/ws-scrcpy.prod.ts:11:42 - error TS7006: Parameter 'args' implicitly has an 'any' type.

11 const back: ConfigurationFactory = (env, args) => {
                                            ~~~~

    at createTSError (/data/home/hanweb/project/python/project/JMCT3.0.3/app/src/ws-scrcpy/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/data/home/hanweb/project/python/project/JMCT3.0.3/app/src/ws-scrcpy/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (/data/home/hanweb/project/python/project/JMCT3.0.3/app/src/ws-scrcpy/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (/data/home/hanweb/project/python/project/JMCT3.0.3/app/src/ws-scrcpy/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (/data/home/hanweb/project/python/project/JMCT3.0.3/app/src/ws-scrcpy/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (/data/home/hanweb/project/python/project/JMCT3.0.3/app/src/ws-scrcpy/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (/data/home/hanweb/project/python/project/JMCT3.0.3/app/src/ws-scrcpy/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/data/home/hanweb/project/python/project/JMCT3.0.3/app/src/ws-scrcpy/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/data/home/hanweb/project/python/project/JMCT3.0.3/app/src/ws-scrcpy/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /data/home/hanweb/project/python/project/JMCT3.0.3/app/src/ws-scrcpy/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/data/home/hanweb/project/python/project/JMCT3.0.3/app/src/ws-scrcpy/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /data/home/hanweb/project/python/project/JMCT3.0.3/app/src/ws-scrcpy/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/data/home/hanweb/project/python/project/JMCT3.0.3/app/src/ws-scrcpy/node_modules/yargs/yargs.js:576:18)
    at /data/home/hanweb/project/python/project/JMCT3.0.3/app/src/ws-scrcpy/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/data/home/hanweb/project/python/project/JMCT3.0.3/app/src/ws-scrcpy/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at runCli (/data/home/hanweb/project/python/project/JMCT3.0.3/app/src/ws-scrcpy/node_modules/webpack/bin/webpack.js:69:2)
    at Object.<anonymous> (/data/home/hanweb/project/python/project/JMCT3.0.3/app/src/ws-scrcpy/node_modules/webpack/bin/webpack.js:162:2)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)

**Comment by yycxx** [comment]
node:18.13.0
npm:8.19.3
webpack:5.75.0
webpack-cli:3.3.12
webpack-node-externals:2.5.2
ts-node:10.9.1

**Comment by drauggres** [comment]
> webpack-cli:3.3.12

https://github.com/NetrisTV/ws-scrcpy/blob/da798b660b69527d4c5300f5884b969af4ae65a6/package.json#L65

**Comment by yycxx** [comment]
The compatibility of webpack and webpack-cli versions. Clear the cache and npm install again to solve this problem

**Comment by yycxx** [comment]
The compatibility of webpack and webpack-cli versions. Clear the cache and re-install to solve this problem
