### ISSUE TITLE
unable to start project

### ISSUE THREAD

**Issue by onlineapps-cloud** [NetrisTV/ws-scrcpy#285]
hi, i tried using this [guide](https://github.com/NetrisTV/ws-scrcpy#build-and-start), but i unable to run succesfully. `error log:
```
user@linux:~/ws-scrcpy

$ npm start

> ws-scrcpy@0.8.1-dev start
> npm run dist && cd dist && npm start


> ws-scrcpy@0.8.1-dev dist
> npm run dist:prod


> ws-scrcpy@0.8.1-dev dist:prod
> webpack --config webpack/ws-scrcpy.prod.ts --stats-error-details

assets by status 6.36 KiB [cached] 2 assets
assets by status 1.02 MiB [compared for emit]
  assets by path *.js 890 KiB
    asset bundle.js 720 KiB [compared for emit] [minimized] [big] (name: main) 1 related asset
    asset bundle.worker.js 170 KiB [compared for emit] [minimized]
  asset avc.wasm 130 KiB [compared for emit] [from: vendor/Broadway/avc.wasm.asset] (auxiliary name: main)
  asset main.css 23.8 KiB [compared for emit] (name: main)
  asset index.html 313 bytes [compared for emit]
Entrypoint main [big] 744 KiB (136 KiB) = main.css 23.8 KiB bundle.js 720 KiB 3 auxiliary assets
orphan modules 34.6 KiB (javascript) 6.44 KiB (runtime) [orphan] 43 modules
runtime modules 1.72 KiB 5 modules
javascript modules 1.05 MiB
  modules by path ./src/ 400 KiB 100 modules
  modules by path ./node_modules/ 597 KiB 26 modules
  modules by path ./vendor/ 81.1 KiB 21 modules
  external "fs" 42 bytes [built] [code generated]
css modules 23.7 KiB
  css ./node_modules/css-loader/dist/cjs.js!./src/style/app.css 4.12 KiB [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./src/style/devicelist.css 4.82 KiB [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./node_modules/xterm/css/xterm.css 4.3 KiB [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./src/style/devtools.css 2.04 KiB [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./src/style/filelisting.css 4.97 KiB [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./src/style/morebox.css 701 bytes [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./src/style/dialog.css 2.82 KiB [built] [code generated]

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  bundle.js (720 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (744 KiB)
      main.css
      bundle.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.76.0 compiled with 3 warnings in 44061 ms

assets by chunk 123 KiB (auxiliary name: main)
  asset vendor/Genymobile/scrcpy/scrcpy-server.jar 110 KiB [compared for emit] [from: vendor/Genymobile/scrcpy/scrcpy-server.jar] (auxiliary name: main)
  asset vendor/Genymobile/scrcpy/LICENSE 11.1 KiB [compared for emit] [from: vendor/Genymobile/scrcpy/LICENSE] (auxiliary name: main)
  asset LICENSE 1.03 KiB [compared for emit] [from: LICENSE] (auxiliary name: main)
asset index.js 84.6 KiB [compared for emit] [minimized] (name: main)
asset package.json 423 bytes [compared for emit]
runtime modules 697 bytes 4 modules
cacheable modules 189 KiB
  modules by path ./src/server/ 144 KiB 28 modules
  modules by path ./src/common/*.ts 6.32 KiB 7 modules
  modules by path ./src/packages/multiplexer/*.ts 21.7 KiB 7 modules
  modules by path ./src/app/ 17.2 KiB 4 modules
  modules by path ./vendor/Genymobile/scrcpy/ 162 bytes 2 modules
  + 2 modules
modules by path external "@dead50f7/adbkit/lib/ 210 bytes
  external "@dead50f7/adbkit/lib/adb/protocol" 42 bytes [built] [code generated]
  external "@dead50f7/adbkit/lib/adb" 42 bytes [built] [code generated]
  external "@dead50f7/adbkit/lib/adb/sync/entry" 42 bytes [built] [code generated]
  external "@dead50f7/adbkit/lib/adb/client" 42 bytes [built] [code generated]
  external "@dead50f7/adbkit/lib/adb/command" 42 bytes [built] [code generated]
+ 18 modules
webpack 5.76.0 compiled successfully in 31602 ms

> ws-scrcpy@0.8.1-dev start
> node ./index.js

/home/user/ws-scrcpy/node_modules/yaml/dist/compose/composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/ws-scrcpy/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code 1
npm ERR! path /home/user/ws-scrcpy/dist
npm ERR! command failed
npm ERR! command sh -c node ./index.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2023-10-17T17_51_49_509Z-debug.log
npm ERR! code 1
npm ERR! path /home/user/ws-scrcpy
npm ERR! command failed
npm ERR! command sh -c npm run dist && cd dist && npm start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2023-10-17T17_51_49_526Z-debug.log
user@linux:~/ws-scrcpy
$ 
```
npm install log:
```
user@linux:~/ws-scrcpy
$ npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'yaml@2.2.2',
npm WARN EBADENGINE   required: { node: '>= 14' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }

up to date, audited 750 packages in 16s

91 packages are looking for funding
  run `npm fund` for details

8 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```
error log from `/home/user/.npm/_logs/2023-10-17T17_51_49_526Z-debug.log`

```
cat /home/user/.npm/_logs/2023-10-17T17_57_47_679Z-debug.log
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
1 info using npm@7.5.2
2 info using node@v12.22.12
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 3ms
5 timing config:load:builtin Completed in 3ms
6 timing config:load:cli Completed in 3ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/home/user/ws-scrcpy/dist/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/home/user/.npmrc Completed in 0ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 15ms
19 verbose npm-session b57e618885ba3fa2
20 timing npm:load Completed in 27ms
21 timing command:run-script Completed in 124ms
22 timing command:start Completed in 126ms
23 verbose stack Error: command failed
23 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
23 verbose stack     at ChildProcess.emit (events.js:314:20)
23 verbose stack     at maybeClose (internal/child_process.js:1022:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
24 verbose pkgid ws-scrcpy@0.8.1-dev
25 verbose cwd /home/user/ws-scrcpy/dist
26 verbose Linux 6.0.0-6mx-amd64
27 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
28 verbose node v12.22.12
29 verbose npm  v7.5.2
30 error code 1
31 error path /home/user/ws-scrcpy/dist
32 error command failed
33 error command sh -c node ./index.js
34 verbose exit 1
```

what i do wrong?. Thanks, best regards

**Comment by drauggres** [comment]
Hi.
Your node `v12.22.12` is too old. Please try with a newer version.

**Comment by onlineapps-cloud** [comment]
hi, i updated nodejs to 18 version, but this not solve problem.
current error log:
```
root@linux:/home/user/ws-scrcpy# npm start

> ws-scrcpy@0.8.1-dev start
> npm run dist && cd dist && npm start


> ws-scrcpy@0.8.1-dev dist
> npm run dist:prod


> ws-scrcpy@0.8.1-dev dist:prod
> webpack --config webpack/ws-scrcpy.prod.ts --stats-error-details

assets by status 6.36 KiB [cached] 2 assets
assets by status 1.02 MiB [compared for emit]
  assets by path *.js 890 KiB
    asset bundle.js 720 KiB [compared for emit] [minimized] [big] (name: main) 1 related asset
    asset bundle.worker.js 170 KiB [compared for emit] [minimized]
  asset avc.wasm 130 KiB [compared for emit] [from: vendor/Broadway/avc.wasm.asset] (auxiliary name: main)
  asset main.css 23.8 KiB [compared for emit] (name: main)
  asset index.html 313 bytes [compared for emit]
Entrypoint main [big] 744 KiB (136 KiB) = main.css 23.8 KiB bundle.js 720 KiB 3 auxiliary assets
orphan modules 34.6 KiB (javascript) 6.44 KiB (runtime) [orphan] 43 modules
runtime modules 1.72 KiB 5 modules
javascript modules 1.05 MiB
  modules by path ./src/ 400 KiB 100 modules
  modules by path ./node_modules/ 597 KiB 26 modules
  modules by path ./vendor/ 81.1 KiB 21 modules
  external "fs" 42 bytes [built] [code generated]
css modules 23.7 KiB
  css ./node_modules/css-loader/dist/cjs.js!./src/style/app.css 4.12 KiB [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./src/style/devicelist.css 4.82 KiB [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./node_modules/xterm/css/xterm.css 4.3 KiB [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./src/style/devtools.css 2.04 KiB [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./src/style/filelisting.css 4.97 KiB [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./src/style/morebox.css 701 bytes [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./src/style/dialog.css 2.82 KiB [built] [code generated]

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  bundle.js (720 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (744 KiB)
      main.css
      bundle.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.76.0 compiled with 3 warnings in 25506 ms

assets by chunk 123 KiB (auxiliary name: main)
  asset vendor/Genymobile/scrcpy/scrcpy-server.jar 110 KiB [compared for emit] [from: vendor/Genymobile/scrcpy/scrcpy-server.jar] (auxiliary name: main)
  asset vendor/Genymobile/scrcpy/LICENSE 11.1 KiB [compared for emit] [from: vendor/Genymobile/scrcpy/LICENSE] (auxiliary name: main)
  asset LICENSE 1.03 KiB [compared for emit] [from: LICENSE] (auxiliary name: main)
asset index.js 84.6 KiB [compared for emit] [minimized] (name: main)
asset package.json 423 bytes [compared for emit]
runtime modules 697 bytes 4 modules
cacheable modules 189 KiB
  modules by path ./src/server/ 144 KiB 28 modules
  modules by path ./src/common/*.ts 6.32 KiB 7 modules
  modules by path ./src/packages/multiplexer/*.ts 21.7 KiB 7 modules
  modules by path ./src/app/ 17.2 KiB 4 modules
  modules by path ./vendor/Genymobile/scrcpy/ 162 bytes 2 modules
  + 2 modules
modules by path external "@dead50f7/adbkit/lib/ 210 bytes
  external "@dead50f7/adbkit/lib/adb/protocol" 42 bytes [built] [code generated]
  external "@dead50f7/adbkit/lib/adb" 42 bytes [built] [code generated]
  external "@dead50f7/adbkit/lib/adb/sync/entry" 42 bytes [built] [code generated]
  external "@dead50f7/adbkit/lib/adb/client" 42 bytes [built] [code generated]
  external "@dead50f7/adbkit/lib/adb/command" 42 bytes [built] [code generated]
+ 18 modules
webpack 5.76.0 compiled successfully in 17040 ms

> ws-scrcpy@0.8.1-dev start
> node ./index.js

innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /home/user/ws-scrcpy/node_modules/node-pty/lib/unixTerminal.js
- /home/user/ws-scrcpy/node_modules/node-pty/lib/index.js
- /home/user/ws-scrcpy/dist/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/user/ws-scrcpy/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/user/ws-scrcpy/node_modules/node-pty/lib/index.js:13:20)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/user/ws-scrcpy/node_modules/node-pty/lib/unixTerminal.js',
    '/home/user/ws-scrcpy/node_modules/node-pty/lib/index.js',
    '/home/user/ws-scrcpy/dist/index.js'
  ]
}
libnode.so.72: cannot open shared object file: No such file or directory

Received signal 1
```
```
root@linux:/home/user/ws-scrcpy# node -v
v18.17.1
root@linux:/home/user/ws-scrcpy# npm -v
9.6.7
```

**Comment by drauggres** [comment]
Try to reinstall dependencies with `npm ci`
Native modules are not compatible between major node.js versions.

**Comment by onlineapps-cloud** [comment]
> Try to reinstall dependencies with `npm ci` Native modules are not compatible between major node.js versions.

this solve problem, i able to start projetc, thanks, best regards.
