### ISSUE TITLE
Issue with Android 14 display in pixel device

### ISSUE THREAD

**Issue by krishtoautomate** [NetrisTV/ws-scrcpy#306]
stdout: java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
        at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getMethod(Class.java:2449)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:104)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:112)
        at com.genymobile.scrcpy.Device.<init>(Device.java:110)
        at com.genymobile.scrcpy.Connection.<init>(Connection.java:37)
[25091FDF6006E3] stdout:        at com.genymobile.scrcpy.WebSocketConnection.<init>(WebSocketConnection.java:23)
        at com.genymobile.scrcpy.WSServer.joinStreamForDisplayId(WSServer.java:163)
[25091FDF6006E3] stdout:        at com.genymobile.scrcpy.WSServer.onMessage(WSServer.java:126)
        at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:648)
        at org.java_websocket.drafts.Draft_6455.processFrameBinary(Draft_6455.java:835)
        at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:794)
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:381)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:218)
        at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1011)
        at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:993)
[25091FDF6006E3] stdout: java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
        at com.genymobile.scrcpy.ScreenEncoder.createDisplay(ScreenEncoder.java:258)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:100)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:82)
        at com.genymobile.scrcpy.ScreenEncoder.run(ScreenEncoder.java:294)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
        at java.lang.Class.getMethod(Class.java:2937)
        at java.lang.Class.getMethod(Class.java:2449)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:81)
        ... 5 more

**Comment by krishtoautomate** [comment]
https://github.com/Genymobile/scrcpy/pull/4657

**Comment by Barney-Steven** [comment]
Hi, Scrcpy 2.4 supports Android 14 + , but the version of scrcpy in ws-scrcpy is way behind, do you fix the issue in ws-scrcpy?

**Comment by krishtoautomate** [comment]
Too many classes to fix. It is like complete rewrite

**Comment by ituberus** [comment]
> Too many classes to fix. It is like complete rewrite

ANy fix soon, my pixel was working about to weeks ago, wanted to use today, its just black, nothing shows, but im still able to operate the phone from the black screen, any fix please?, sorry for my bad english
![shades](https://github.com/NetrisTV/ws-scrcpy/assets/34318384/16802c5e-32ed-4c98-96d0-6721c9942eff)
