### ISSUE TITLE
Android 15 support

### ISSUE THREAD

**Issue by Okra0o0** [NetrisTV/ws-scrcpy#315]
Currently  Android 15 devices have no screen, but it can be control,  whether it's scrcpy-server.jar problem, can you fix it? Thanks~

**Comment by ituberus** [comment]
> Currently Android 15 devices have no screen, but it can be control, whether it's scrcpy-server.jar problem, can you fix it? Thanks~

Yeah, been trying to create scrcpy-server.jar from the latest version of scrcpy, but to no avail

**Comment by Okra0o0** [comment]
> > Currently Android 15 devices have no screen, but it can be control, whether it's scrcpy-server.jar problem, can you fix it? Thanks~
> 
> Yeah, been trying to create scrcpy-server.jar from the latest version of scrcpy, but to no avail

I also trid the Genymobile/scrcpy v2.5, but it didn't work, after all, Genymobile/scrcpy has committed many versions

**Comment by Okra0o0** [comment]
> > Currently Android 15 devices have no screen, but it can be control, whether it's scrcpy-server.jar problem, can you fix it? Thanks~
> 
> Yeah, been trying to create scrcpy-server.jar from the latest version of scrcpy, but to no avail

With this Issue [4657](https://github.com/Genymobile/scrcpy/pull/4657), I modified the source code based on NetrisTV/scrcpy version 1.19 and compiled a new version of the scrcpy-server.jar. It can work in Android 15 beta.

**Comment by ituberus** [comment]
> > > Currently Android 15 devices have no screen, but it can be control, whether it's scrcpy-server.jar problem, can you fix it? Thanks~
> > 
> > 
> > Yeah, been trying to create scrcpy-server.jar from the latest version of scrcpy, but to no avail
> 
> With this Issue [4657](https://github.com/Genymobile/scrcpy/pull/4657), I modified the source code based on NetrisTV/scrcpy version 1.19 and compiled a new version of the scrcpy-server.jar. It can work in Android 15 beta.

HI, i would appreciate if you could share your scrcpy-server.jar with me, been trying to do it myself but no success, thanks

**Comment by Okra0o0** [comment]
> > > > Currently Android 15 devices have no screen, but it can be control, whether it's scrcpy-server.jar problem, can you fix it? Thanks~
> > > 
> > > 
> > > Yeah, been trying to create scrcpy-server.jar from the latest version of scrcpy, but to no avail
> > 
> > 
> > With this Issue [4657](https://github.com/Genymobile/scrcpy/pull/4657), I modified the source code based on NetrisTV/scrcpy version 1.19 and compiled a new version of the scrcpy-server.jar. It can work in Android 15 beta.
> 
> HI, i would appreciate if you could share your scrcpy-server.jar with me, been trying to do it myself but no success, thanks

You can give it a try, although it needs to be optimized.
[scrcpy-server15.zip](https://github.com/user-attachments/files/16438192/scrcpy-server15.zip)

**Comment by ituberus** [comment]
> > > > > Currently Android 15 devices have no screen, but it can be control, whether it's scrcpy-server.jar problem, can you fix it? Thanks~
> > > > 
> > > > 
> > > > Yeah, been trying to create scrcpy-server.jar from the latest version of scrcpy, but to no avail
> > > 
> > > 
> > > With this Issue [4657](https://github.com/Genymobile/scrcpy/pull/4657), I modified the source code based on NetrisTV/scrcpy version 1.19 and compiled a new version of the scrcpy-server.jar. It can work in Android 15 beta.
> > 
> > 
> > HI, i would appreciate if you could share your scrcpy-server.jar with me, been trying to do it myself but no success, thanks
> 
> You can give it a try, although it needs to be optimized. [scrcpy-server15.zip](https://github.com/user-attachments/files/16438192/scrcpy-server15.zip)

It worked, thanks man

**Comment by denizkoele** [comment]
@Okra0o0 I've tried it with your updated scrcpy server and it didnt worked with android 14 pixel.
Which scrcpy version did you use for it?

or may i see your codebase to debug?

Check out this issue:
https://github.com/NetrisTV/ws-scrcpy/issues/306

**Comment by Okra0o0** [comment]
> @Okra0o0 I've tried it with your updated scrcpy server and it didnt worked with android 14 pixel. Which scrcpy version did you use for it?
> 
> or may i see your codebase to debug?
> 
> Check out this issue: #306

**Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]**
---> SurfaceControl  will be deprecated in new version, so change to VirtualDisplay. Associated files such as attachments. And these changes  based on NetrisTV/scrcpy version 1.19 branch. By the way, it worked in my android 14 (AP1A.240405.019.A1) pixel 6 pro.
[java.zip](https://github.com/user-attachments/files/16576931/java.zip)

**Comment by eschoenawa** [comment]
@Okra0o0 can you give some instruction what to do with the attached files? I'm assuming by the heart reactions it fixes the issue...

**Comment by eschoenawa** [comment]
I tried, but the screen of my Pixel remained blank :eyes: . It works fine with a xiaomi device... I'm just running npm start after replacing the jar, is that enough or even more required?

**Comment by denizkoele** [comment]
Yes it haven't worked with my pixel at first time too. After clearing caches, few pc restarts and phone restarts it suddenly started to work. Idk what of them exactly fixed the problem

**Comment by eschoenawa** [comment]
Awesome, a reboot did indeed fix the issue.

@Okra0o0 could you still share your changes somewhere? I'd like to be able to further customize the server jar.

**Comment by denizkoele** [comment]
> Awesome, a reboot did indeed fix the issue.
> 
> @Okra0o0 could you still share your changes somewhere? I'd like to be able to further customize the server jar.

Here you go [java.zip](https://github.com/user-attachments/files/16576931/java.zip)

Credits to @Okra0o0

**Comment by eschoenawa** [comment]
So those four files are the only changes in the scrcpy fork we have to make to build that jar?

I saw them earlier, but thought that can't be it 😅 .

**Comment by SPrasadT** [comment]
awesome! thanks @Okra0o0 and thanks everyone! for this support.

**Comment by drauggres** [comment]
Hi everyone. Please check #344

**Comment by Okra0o0** [comment]
> Hi everyone. Please check #344

I tested phones with both 14 and 15 system on the [feature/android_14_15](https://github.com/drauggres/ws-scrcpy/tree/feature/android_14_15) branch. It encountered the following errors. 
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
        at java.lang.Class.getMethod(Class.java:2950)
        at java.lang.Class.getMethod(Class.java:2450)
		at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:104)
        at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:112)
        at com.genymobile.scrcpy.Device.<init>(Device.java:110)
        at com.genymobile.scrcpy.Connection.<init>(Connection.java:37)
        at com.genymobile.scrcpy.WebSocketConnection.<init>(WebSocketConnection.java:23)
		at com.genymobile.scrcpy.WSServer.joinStreamForDisplayId(WSServer.java:163)
        at com.genymobile.scrcpy.WSServer.onMessage(WSServer.java:126)
        at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:648)
        at org.java_websocket.drafts.Draft_6455.processFrameBinary(Draft_6455.java:835)
        at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:794)
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:381)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:218)
        at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1011)
        at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:993)

**Comment by Okra0o0** [comment]
> Hi everyone. Please check #344

I tested phones with both 14 and 15 system on the [feature/android_14_15](https://github.com/drauggres/ws-scrcpy/tree/feature/android_14_15) branch. It encountered the following errors.
  java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
  at java.lang.Class.getMethod(Class.java:2950)
  at java.lang.Class.getMethod(Class.java:2450)
  at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:104)
  at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:112)
  at com.genymobile.scrcpy.Device.(Device.java:110)
  at com.genymobile.scrcpy.Connection.(Connection.java:37)
  at com.genymobile.scrcpy.WebSocketConnection.(WebSocketConnection.java:23)
  at com.genymobile.scrcpy.WSServer.joinStreamForDisplayId(WSServer.java:163)
  at com.genymobile.scrcpy.WSServer.onMessage(WSServer.java:126)
  at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:648)
  at org.java_websocket.drafts.Draft_6455.processFrameBinary(Draft_6455.java:835)
  at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:794)
  at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:381)
  at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:218)
  at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1011)
  at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:993)

**Comment by Okra0o0** [comment]
> Hi everyone. Please check #344

I tested phones with both 14 and 15 system on the [feature/android_14_15](https://github.com/drauggres/ws-scrcpy/tree/feature/android_14_15) branch. It encountered the following errors.

      java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
      at java.lang.Class.getMethod(Class.java:2950)
      at java.lang.Class.getMethod(Class.java:2450)
      at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:104)
      at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:112)
      at com.genymobile.scrcpy.Device.(Device.java:110)
      at com.genymobile.scrcpy.Connection.(Connection.java:37)
      at com.genymobile.scrcpy.WebSocketConnection.(WebSocketConnection.java:23)
      at com.genymobile.scrcpy.WSServer.joinStreamForDisplayId(WSServer.java:163)
      at com.genymobile.scrcpy.WSServer.onMessage(WSServer.java:126)
      at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:648)
      at org.java_websocket.drafts.Draft_6455.processFrameBinary(Draft_6455.java:835)
      at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:794)
      at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:381)
      at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:218)
      at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1011)
      at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:993)

I have experienced this before and then made a another version of the scrcpy-server. 
[scrcpy.zip](https://github.com/user-attachments/files/18317917/scrcpy.zip)
[scrcpy-server(1.19-ws6).jar.zip](https://github.com/user-attachments/files/18317923/scrcpy-server.1.19-ws6.jar.zip)

**Comment by drauggres** [comment]
Hi, @Okra0o0. Could you open PR in https://github.com/NetrisTV/scrcpy?

**Comment by Okra0o0** [comment]
> Hi, @Okra0o0. Could you open PR in https://github.com/NetrisTV/scrcpy?

 Looks likeI can't.
    remote: Permission to NetrisTV/scrcpy.git denied to Okra0o0.
    fatal: unable to access 'https://github.com/NetrisTV/scrcpy.git/': The requested URL returned error: 403

**Comment by drauggres** [comment]
You need to create a fork. Then create a new branch in you fork from `feature/websocket-v1.19.x` and add commits to it. After that open new PR to NetrisTV/scrcpy.
![image](https://github.com/user-attachments/assets/2e81045c-721e-47d3-961a-32037aab57d1)

**Comment by Okra0o0** [comment]
> You need to create a fork. Then create a new branch in you fork from `feature/websocket-v1.19.x` and add commits to it. After that open new PR to NetrisTV/scrcpy. ![image](https://private-user-images.githubusercontent.com/7796592/400399115-2e81045c-721e-47d3-961a-32037aab57d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNjA5MjcsIm5iZiI6MTczNjE2MDYyNywicGF0aCI6Ii83Nzk2NTkyLzQwMDM5OTExNS0yZTgxMDQ1Yy03MjFlLTQ3ZDMtOTYxYS0zMjAzN2FhYjU3ZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDZUMTA1MDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjU5MzAxOTlhMWVkNjA1MzA1MzNjYmI4Yzc4Y2JhZjk4NzhmOWNlMzgwNTA1NmFlYzU2Yjc1Yzg1MTdlN2Q0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ajh1oXCXP1E9SlnFHnbB-AomzaOEEmzRGUZRak4outQ)

Oh, I see, thank you.
Excuse me, I made a mistake, this [feature/android_14_15](https://github.com/drauggres/ws-scrcpy/tree/feature/android_14_15) branch has already fixed the screen problem. Just need to choose [H264 Converter].
