### ISSUE TITLE
ubuntu24 错误

### ISSUE THREAD

**Issue by wode2016501** [NetrisTV/ws-scrcpy#317]
src/ws-scrcpy$ npm start

> ws-scrcpy@0.9.0-dev start
> npm run dist && cd dist && npm start

> ws-scrcpy@0.9.0-dev dist
> npm run dist:prod

> ws-scrcpy@0.9.0-dev dist:prod
> webpack --config webpack/ws-scrcpy.prod.ts --stats-error-details

assets by status 6.36 KiB [cached] 2 assets
assets by status 1.02 MiB [compared for emit]
  assets by path *.js 893 KiB
    asset bundle.js 723 KiB [compared for emit] [minimized] [big] (name: main) 1 related asset
    asset bundle.worker.js 170 KiB [compared for emit] [minimized]
  asset avc.wasm 130 KiB [compared for emit] [from: vendor/Broadway/avc.wasm.asset] (auxiliary name: main)
  asset main.css 23.8 KiB [compared for emit] (name: main)
  asset index.html 313 bytes [compared for emit]
Entrypoint main [big] 747 KiB (136 KiB) = main.css 23.8 KiB bundle.js 723 KiB 3 auxiliary assets
orphan modules 33.6 KiB (javascript) 6.44 KiB (runtime) [orphan] 43 modules
runtime modules 1.81 KiB 5 modules
javascript modules 1.06 MiB
  modules by path ./src/ 401 KiB 100 modules
  modules by path ./node_modules/ 601 KiB 26 modules
  modules by path ./vendor/ 81.1 KiB 21 modules
  external "fs" 42 bytes [built] [code generated]
css modules 23.7 KiB
  css ./node_modules/css-loader/dist/cjs.js!./src/style/app.css 4.12 KiB [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./src/style/devicelist.css 4.82 KiB [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./node_modules/xterm/css/xterm.css 4.3 KiB [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./src/style/devtools.css 2.04 KiB [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./src/style/filelisting.css 4.97 KiB [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./src/style/morebox.css 701 bytes [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./src/style/dialog.css 2.82 KiB [built] [code generated]

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  bundle.js (723 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (747 KiB)
      main.css
      bundle.js

WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.90.3 compiled with 3 warnings in 38675 ms

assets by chunk 123 KiB (auxiliary name: main)
  asset vendor/Genymobile/scrcpy/scrcpy-server.jar 110 KiB [compared for emit] [from: vendor/Genymobile/scrcpy/scrcpy-server.jar] (auxiliary name: main)
  asset vendor/Genymobile/scrcpy/LICENSE 11.1 KiB [compared for emit] [from: vendor/Genymobile/scrcpy/LICENSE] (auxiliary name: main)
  asset LICENSE 1.03 KiB [compared for emit] [from: LICENSE] (auxiliary name: main)
asset index.js 84.8 KiB [compared for emit] [minimized] (name: main)
asset package.json 424 bytes [compared for emit]
runtime modules 697 bytes 4 modules
cacheable modules 190 KiB
  modules by path ./src/server/ 144 KiB 28 modules
  modules by path ./src/common/*.ts 6.32 KiB 7 modules
  modules by path ./src/packages/multiplexer/*.ts 21.7 KiB 7 modules
  modules by path ./src/app/ 17.2 KiB 4 modules
  modules by path ./vendor/Genymobile/scrcpy/ 162 bytes 2 modules
  + 2 modules
modules by path external "@dead50f7/adbkit/lib/ 210 bytes
  external "@dead50f7/adbkit/lib/adb/protocol" 42 bytes [built] [code generated]
  external "@dead50f7/adbkit/lib/adb" 42 bytes [built] [code generated]
  external "@dead50f7/adbkit/lib/adb/sync/entry" 42 bytes [built] [code generated]
  external "@dead50f7/adbkit/lib/adb/client" 42 bytes [built] [code generated]
  external "@dead50f7/adbkit/lib/adb/command" 42 bytes [built] [code generated]
+ 18 modules
webpack 5.90.3 compiled successfully in 26580 ms

> ws-scrcpy@0.9.0-dev start
> node ./index.js

/mnt/656F8E3145175D32/ubuntu/src/ws-scrcpy/node_modules/yaml/dist/compose/composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/mnt/656F8E3145175D32/ubuntu/src/ws-scrcpy/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
wode@ubuntu:~/src/ws-scrcpy$ gvim /mnt/656F8E3145175D32/ubuntu/src/ws-scrcpy/node_modules/yaml/dist/compose/composer.js

(gvim:29622): IBUS-WARNING **: 20:18:01.639: The owner of /home/wode/.config/ibus/bus is not wode!

**Comment by WilsonScott** [comment]
same issue
