### ISSUE TITLE
Notsupport android15: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay

### ISSUE THREAD

**Issue by wangyuc** [NetrisTV/ws-scrcpy#337]
Scrcpy 3.0 can be used normally.
But use ws-scrcpy  the screen on web is black , it cannot be seen.

console error:
stdout: java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
        at com.genymobile.scrcpy.ScreenEncoder.createDisplay(ScreenEncoder.java:258)
        at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:100)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:82)
        at com.genymobile.scrcpy.ScreenEncoder.run(ScreenEncoder.java:294)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
        at java.lang.Class.getMethod(Class.java:2950)
        at java.lang.Class.getMethod(Class.java:2450)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:81)
        ... 5 more

**Comment by wangyuc** [comment]
https://github.com/NetrisTV/ws-scrcpy/issues/315
