### ISSUE TITLE
failed to spawn adb process

### ISSUE THREAD

**Issue by Chosenooo** [NetrisTV/ws-scrcpy#77]
Hello
I ran into a problem with the ws-scrcpy project.
eg:
```
failed to spawn adb process.
Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Error: spawn adb ENOENT
[192.168.0.102:5555] Error: spawn adb ENOENT
[192.168.0.102:5555] adb process (-s 192.168.0.102:5555 shell CLASSPATH=/data/local/tmp/scrcpy-server.jar nohup app_process / com.genymobile.scrcpy.Server 1.17-ws5 web ERROR 8886 2>&1 > /dev/null) exited with code -4058
```
What should I do? I hope to get your help.

**Comment by drauggres** [comment]
Hi. Verify that you have `adb` (or `adb.exe` on Windows) available in the `PATH` environment variable.

**Comment by Chosenooo** [comment]
I have the configuration in scrcpy-win64-v1.17 adb.exe To the path environment variable

But there will still be this mistake

**Comment by drauggres** [comment]
What happens if you run `adb devices` instead of `npm start`?

**Comment by Chosenooo** [comment]
Oh, I think I know what's going on, thanks!

**Comment by drauggres** [comment]
> Oh, I think I know what's going on, thanks!

It would be helpful for others if you share what was the problem.

**Comment by Chosenooo** [comment]
> > Oh, I think I know what's going on, thanks!
> 
> It would be helpful for others if you share what was the problem.
Well, I encountered an abnormal configuration of the ADB path of the path environment variable
